version: '3.8'

services:
  nginx:
    image: crpi-995uocus6og9mdf4.cn-beijing.personal.cr.aliyuncs.com/wuwenlong797/nginx:alpine
    ports:
      - "80:80"  
    volumes:
      - ./build:/usr/share/nginx/html  # 将构建后的文件挂载到容器中
      - ./nginx.conf:/etc/nginx/nginx.conf  # 将自定义的 Nginx 配置挂载到容器中
    restart: always  # 容器崩溃时自动重启